// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.11.4
// source: geocoding.proto

package geocodingpb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GeocodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Location string `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
}

func (x *GeocodeRequest) Reset() {
	*x = GeocodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_geocoding_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeocodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeocodeRequest) ProtoMessage() {}

func (x *GeocodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geocoding_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeocodeRequest.ProtoReflect.Descriptor instead.
func (*GeocodeRequest) Descriptor() ([]byte, []int) {
	return file_geocoding_proto_rawDescGZIP(), []int{0}
}

func (x *GeocodeRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type GeocodeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Latitude         float64 `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude        float64 `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	FormattedAddress string  `protobuf:"bytes,3,opt,name=formattedAddress,proto3" json:"formattedAddress,omitempty"`
}

func (x *GeocodeReply) Reset() {
	*x = GeocodeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_geocoding_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeocodeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeocodeReply) ProtoMessage() {}

func (x *GeocodeReply) ProtoReflect() protoreflect.Message {
	mi := &file_geocoding_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeocodeReply.ProtoReflect.Descriptor instead.
func (*GeocodeReply) Descriptor() ([]byte, []int) {
	return file_geocoding_proto_rawDescGZIP(), []int{1}
}

func (x *GeocodeReply) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GeocodeReply) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GeocodeReply) GetFormattedAddress() string {
	if x != nil {
		return x.FormattedAddress
	}
	return ""
}

var File_geocoding_proto protoreflect.FileDescriptor

var file_geocoding_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x67, 0x65, 0x6f, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0b, 0x67, 0x65, 0x6f, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x70, 0x62, 0x22, 0x2c,
	0x0a, 0x0e, 0x47, 0x65, 0x6f, 0x63, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x74, 0x0a, 0x0c,
	0x47, 0x65, 0x6f, 0x63, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1a, 0x0a, 0x08,
	0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08,
	0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67,
	0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x6c, 0x6f, 0x6e,
	0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74,
	0x74, 0x65, 0x64, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x10, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x74, 0x65, 0x64, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x32, 0x4e, 0x0a, 0x07, 0x47, 0x65, 0x6f, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x43, 0x0a,
	0x07, 0x47, 0x65, 0x6f, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x1b, 0x2e, 0x67, 0x65, 0x6f, 0x63, 0x6f,
	0x64, 0x69, 0x6e, 0x67, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x6f, 0x63, 0x6f, 0x64, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x67, 0x65, 0x6f, 0x63, 0x6f, 0x64, 0x69, 0x6e,
	0x67, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x6f, 0x63, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x00, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x3b, 0x67, 0x65, 0x6f, 0x63, 0x6f, 0x64, 0x69, 0x6e,
	0x67, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_geocoding_proto_rawDescOnce sync.Once
	file_geocoding_proto_rawDescData = file_geocoding_proto_rawDesc
)

func file_geocoding_proto_rawDescGZIP() []byte {
	file_geocoding_proto_rawDescOnce.Do(func() {
		file_geocoding_proto_rawDescData = protoimpl.X.CompressGZIP(file_geocoding_proto_rawDescData)
	})
	return file_geocoding_proto_rawDescData
}

var file_geocoding_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_geocoding_proto_goTypes = []interface{}{
	(*GeocodeRequest)(nil), // 0: geocodingpb.GeocodeRequest
	(*GeocodeReply)(nil),   // 1: geocodingpb.GeocodeReply
}
var file_geocoding_proto_depIdxs = []int32{
	0, // 0: geocodingpb.Geocode.Geocode:input_type -> geocodingpb.GeocodeRequest
	1, // 1: geocodingpb.Geocode.Geocode:output_type -> geocodingpb.GeocodeReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_geocoding_proto_init() }
func file_geocoding_proto_init() {
	if File_geocoding_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_geocoding_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GeocodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_geocoding_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GeocodeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_geocoding_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_geocoding_proto_goTypes,
		DependencyIndexes: file_geocoding_proto_depIdxs,
		MessageInfos:      file_geocoding_proto_msgTypes,
	}.Build()
	File_geocoding_proto = out.File
	file_geocoding_proto_rawDesc = nil
	file_geocoding_proto_goTypes = nil
	file_geocoding_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GeocodeClient is the client API for Geocode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GeocodeClient interface {
	Geocode(ctx context.Context, in *GeocodeRequest, opts ...grpc.CallOption) (*GeocodeReply, error)
}

type geocodeClient struct {
	cc grpc.ClientConnInterface
}

func NewGeocodeClient(cc grpc.ClientConnInterface) GeocodeClient {
	return &geocodeClient{cc}
}

func (c *geocodeClient) Geocode(ctx context.Context, in *GeocodeRequest, opts ...grpc.CallOption) (*GeocodeReply, error) {
	out := new(GeocodeReply)
	err := c.cc.Invoke(ctx, "/geocodingpb.Geocode/Geocode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GeocodeServer is the server API for Geocode service.
type GeocodeServer interface {
	Geocode(context.Context, *GeocodeRequest) (*GeocodeReply, error)
}

// UnimplementedGeocodeServer can be embedded to have forward compatible implementations.
type UnimplementedGeocodeServer struct {
}

func (*UnimplementedGeocodeServer) Geocode(context.Context, *GeocodeRequest) (*GeocodeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Geocode not implemented")
}

func RegisterGeocodeServer(s *grpc.Server, srv GeocodeServer) {
	s.RegisterService(&_Geocode_serviceDesc, srv)
}

func _Geocode_Geocode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeocodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeocodeServer).Geocode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/geocodingpb.Geocode/Geocode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeocodeServer).Geocode(ctx, req.(*GeocodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Geocode_serviceDesc = grpc.ServiceDesc{
	ServiceName: "geocodingpb.Geocode",
	HandlerType: (*GeocodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Geocode",
			Handler:    _Geocode_Geocode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "geocoding.proto",
}
